---
title: Publications
---

<style>
  .preprints ol {
    list-style-type:none;
    counter-reset:item 4;
  }
  .preprints ol > li {
    counter-increment:item -1;
  }
  .preprints ol > li::marker {
    content: "[P" counter(item) "]  ";
  }
  .preprints a {font-weight: bold;}

  .journals ol {
    list-style-type:none;
    counter-reset:item 12;
  }
  .journals ol > li {
    counter-increment:item -1;
  }
  .journals ol > li::marker {
    content: "[" counter(item) "]  ";
  }
  .journals a {font-weight: bold;}
</style>

### Preprints
:::{.preprints}
1. **Akash Harapanahalli**, Samuel Coogan, "[Parametric Reachable Sets Via Controlled Dynamical Embeddings.](https://arxiv.org/abs/2504.06955)" To appear in 2025 64th IEEE Conference on Decision and Control (**CDC**), 2025. \[[pdf](https://arxiv.org/pdf/2504.06955)\] 
1. **Akash Harapanahalli**, Samuel Coogan, "[A Linear Differential Inclusion for Contraction Analysis to Known Trajectories.](https://arxiv.org/abs/2411.11587)" In submission, 2024. \[[pdf](https://arxiv.org/pdf/2411.11587)\] \[[slides](/presentations/2024CDC_LDIcontr/)\]
1. **Akash Harapanahalli**, Samuel Coogan, "[Certified Robust Invariant Polytope Training in Neural Controlled ODEs.](https://arxiv.org/abs/2408.01273)" In submission, 2024. \[[pdf](https://arxiv.org/pdf/2408.01273)\] \[[code](https://github.com/gtfactslab/Polytope-Training)\] \[[slides](/presentations/2025VNNCS_workshop/)\]
:::

### Conferences and Journals

:::{.journals}
1. Brendan Gould, **Akash Harapanahalli**, Samuel Coogan "[Automatic and Scalable Safety Verification Using Interval Reachability With Subspace Sampling.](https://ieeexplore.ieee.org/document/11047533/)", Published in IEEE Control Systems Letters (**L-CSS**), 2025.
1. **Akash Harapanahalli**, Samuel Coogan, "[A Global Coordinate-Free Approach to Invariant Contraction on Homogeneous Manifolds.](https://arxiv.org/abs/2410.15441)" Appeared in 2025 American Control Conference (**ACC**), 2025. \[[pdf](https://arxiv.org/pdf/2410.15441)\] \[[slides](/presentations/2025ACC_Homogeneous/)\]
1. **Akash Harapanahalli**, Samuel Coogan, "[Efficient Reachable Sets on Lie Groups Using Lie Algebra Monotonicity and Tangent Intervals.](https://arxiv.org/abs/2403.16214)" Appeared in 2024 63rd IEEE Conference on Decision and Control (**CDC**), 2024. **Runner-Up for the Hybrid Systems Technical Committee Outstanding Student Paper Prize** \[[pdf](https://arxiv.org/pdf/2403.16214)\] \[[slides](/presentations/2024CDC_liereach/)\] 
1. **Akash Harapanahalli**, Saber Jafarpour, Samuel Coogan, "[immrax: A Parallelizable and Differentiable Toolbox for Interval Analysis and Mixed Monotone Reachability in JAX.](https://arxiv.org/abs/2401.11608)" Appeared in The 8th IFAC Conference on Analysis and Design of Hybrid Systems (**ADHS**), 2024. \[[pdf](https://arxiv.org/pdf/2401.11608)\] \[[github](https://github.com/gtfactslab/immrax)\] \[[slides](/presentations/2024ADHS_immrax/)\]
1. Saber Jafarpour\*, **Akash Harapanahalli**\*, Samuel Coogan, "[Efficient Interaction-Aware Interval Analysis of Neural Network Feedback Loops.](https://doi.org/10.1109/TAC.2024.3420968)" Published in IEEE Transactions on Automatic Control (**TAC**), 2024. \[[pdf](https://arxiv.org/pdf/2307.14938)\]
1. **Akash Harapanahalli**, Saber Jafarpour, Samuel Coogan, "[Forward Invariance in Neural Network Controlled Systems.](https://doi.org/10.1109/LCSYS.2023.3341980)" Published in IEEE Control Systems Letters (**L-CSS**), 2023. \[[pdf](https://arxiv.org/pdf/2309.09043)\] \[[slides](/presentations/2024ACC_Invariance/)\]
1. Luke Baird, **Akash Harapanahalli**, Samuel Coogan, "[Interval Signal Temporal Logic From Natural Inclusion Functions.](https://doi.org/10.1109/LCSYS.2023.3337744)" Published in IEEE Control Systems Letters (**L-CSS**), 2023. \[[pdf](https://arxiv.org/pdf/2309.10686)\]
1. **Akash Harapanahalli**, Saber Jafarpour, Samuel Coogan, "[Contraction-Guided Adaptive Partitioning for Reachability Analysis of Neural Network Controlled Systems.](https://doi.org/10.1109/CDC49753.2023.10383360)" Appeared in 2023 62nd IEEE Conference on Decision and Control (**CDC**), 2023. \[[pdf](https://arxiv.org/pdf/2304.03671)\] \[[slides](/files/2023CDC_ContractionGuidedPresentation.pdf)\]
1. **Akash Harapanahalli**, Saber Jafarpour, Samuel Coogan, "[A Toolbox for Fast Interval Arithmetic in numpy with an Application to Formal Verification of Neural Network Controlled Systems.](https://arxiv.org/abs/2306.15340)" Appeared in 2nd Workshop on Formal Verification of Machine Learning (**WFVML**), 2023. \[[pdf](https://arxiv.org/pdf/2306.15340)\] \[[github](https://github.com/gtfactslab/npinterval)\] \[[poster](/files/2023WFVML_npintervalPoster.pdf)\] 
1. Saber Jafarpour\*, **Akash Harapanahalli**\*, Samuel Coogan, "[Interval Reachability of Nonlinear Dynamical Systems with Neural Network Controllers.](https://proceedings.mlr.press/v211/jafarpour23a.html)" Appeared in The 5th Annual Learning for Dynamics and Control Conference (**L4DC**), 2023. \[[pdf](https://arxiv.org/pdf/2301.07912)\] \[[poster](/files/2023L4DC_IntervalReachPoster.pdf)\]
1. **Akash Harapanahalli**\*, Emil Muly\*, Hogan Welch\*, Timothy Brumfiel\*, Zhengyang Weng\*, Manzano Akhtar, Ahmed Abouelnasr, Austin Newland, James Bunting, Kevin McGorrey, Juo Lee, Gaorong Wang, Luke Drnach, Don Lee, Ye Zhao, "[Towards a Biomimetic and Dexterous Robot Avatar: Design, Control, and Kinematics Considerations.](https://akashhara.com/files/AIM_2020_Athena.pdf)" **Best Latest Breaking Results Poster** at 2020 IEEE/ASME International Conference on Advanced Intelligent Mechatronics (**AIM**), 2020. **First Place in the Hardware, Devices & Robotics Track of the 2021 GaTech VIP Innovation Competition**. \[[abstract](/files/Athena_Abstract.pdf)\] \[[poster](/files/Athena_Poster.pdf)\] \[[video](https://www.youtube.com/watch?v=xN51JtM-6LU)\]
:::

\* *indicates equal contribution*